//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionDAM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size BrowEmisoresSize {
            get {
                return ((global::System.Drawing.Size)(this["BrowEmisoresSize"]));
            }
            set {
                this["BrowEmisoresSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BrowEmisoresLocation {
            get {
                return ((global::System.Drawing.Point)(this["BrowEmisoresLocation"]));
            }
            set {
                this["BrowEmisoresLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maximized")]
        public string BrowEmisoresState {
            get {
                return ((string)(this["BrowEmisoresState"]));
            }
            set {
                this["BrowEmisoresState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size BrowClientesSize {
            get {
                return ((global::System.Drawing.Size)(this["BrowClientesSize"]));
            }
            set {
                this["BrowClientesSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BrowClientesLocation {
            get {
                return ((global::System.Drawing.Point)(this["BrowClientesLocation"]));
            }
            set {
                this["BrowClientesLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maximized")]
        public string BrowClientesState {
            get {
                return ((string)(this["BrowClientesState"]));
            }
            set {
                this["BrowClientesState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size BrowTiposDeIVASize {
            get {
                return ((global::System.Drawing.Size)(this["BrowTiposDeIVASize"]));
            }
            set {
                this["BrowTiposDeIVASize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BrowTiposDeIVALocation {
            get {
                return ((global::System.Drawing.Point)(this["BrowTiposDeIVALocation"]));
            }
            set {
                this["BrowTiposDeIVALocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maximized")]
        public string BrowTiposDeIVAState {
            get {
                return ((string)(this["BrowTiposDeIVAState"]));
            }
            set {
                this["BrowTiposDeIVAState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size BrowProductoSize {
            get {
                return ((global::System.Drawing.Size)(this["BrowProductoSize"]));
            }
            set {
                this["BrowProductoSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BrowProductoLocation {
            get {
                return ((global::System.Drawing.Point)(this["BrowProductoLocation"]));
            }
            set {
                this["BrowProductoLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maximized")]
        public string BrowProductoState {
            get {
                return ((string)(this["BrowProductoState"]));
            }
            set {
                this["BrowProductoState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size BrowConceptosFacSize {
            get {
                return ((global::System.Drawing.Size)(this["BrowConceptosFacSize"]));
            }
            set {
                this["BrowConceptosFacSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BrowConceptosFacLocation {
            get {
                return ((global::System.Drawing.Point)(this["BrowConceptosFacLocation"]));
            }
            set {
                this["BrowConceptosFacLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maximized")]
        public string BrowConceptosFacState {
            get {
                return ((string)(this["BrowConceptosFacState"]));
            }
            set {
                this["BrowConceptosFacState"] = value;
            }
        }
    }
}
